### ISSUE TITLE
How to ensure proper usage...?

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/use-deep-compare-effect#2]
Most of the time people should use React.useEffect as @gaearon mentions on twitter and: https://github.com/facebook/react/issues/14476#issuecomment-471199055

I'm really concerned that this package will be used when React.useEffect + React.useMemo or JSON.stringify would be better for everyone.

So I'd like to use this issue for people to raise concrete (NOT ABSTRACT) situations where they feel like they need this package and we can determine whether this package is actually needed for that use case. We're all learning new things here with hooks so it's understandable that we could get things wrong and maybe we're not doing things "the hooks way" yet.

Once we know real scenarios then maybe we can think of ways to document this package (and maybe even add runtime warnings) to avoid people using it when they should use React.useEffect (like [we already do](https://github.com/kentcdodds/use-deep-compare-effect/blob/ea5820448611969c81102ddc71708d4c7ffc0400/src/index.js#L4-L15)).

So please, share your concrete examples!

**Comment by baddox** [comment]
I think you mean

> I'm really concerned that this package will be used *when* React.useEffect...

**Comment by kentcdodds** [comment]
Thanks. Fixed.

**Comment by dusty** [comment]
I am wrapping an existing angular1 app inside a react app and replacing the angular routes with react-router.  

When I come across an angular component in my routes, I'm mounting a react component named AngularComponent that takes a component name as a prop.  This component name is then transformed into an html element with the incoming route params as properties that are loaded into scope, and is compiled by angular and attached to the dom on a ref.

So, I need to know when I should destroy current scope and re-render the angular component. 
 
I'm looking at the component name that is passed, the location.search and match.params.  

eg:
```
<Route path="/my-angular-component/:somePathParam" component={AngularComponent} angularComponent="myAngularComponent" />

becomes...
<AngularComponent component="myAngularComponent" />

loads...
export default function AngularComponent({component, location={}, match={}}) {
  useDeepCompareEffect(() => {
    renderAngular()
    return () => destroyScope()
  }, [component, match.params, location.search])
}

renders...
<my-angular-component some-path-param="somePathParam"></my-angular-component>
```

So, what do you think?  I know it's crazy!  I mean what do you think about use-deep-compare-effect usage? :)

**Comment by kentcdodds** [comment]
Yeah, this definitely feels like a legit use case. You _could_ just use JSON.stringify, but this is more clear/feels less hacky to me.

**Comment by andrevinsky** [comment]
@kentcdodds, hi, please help me see what I am overlooking. You actually suggested using `JSON.stringify` and everyone knows (I am sure you do, for one) how it can break things apart.  As, for instance, `{ a: 0, b: 1 }` and `{ b: 1, a: 0 }` are deep-equal. However, their JSON representation will show inequality right away.

**Comment by kentcdodds** [comment]
Can you give me a _real world_ example where that would be a problem?

**Comment by selbekk** [comment]
Here's an example I couldn't solve any other way:

My custom hook is passed a consumer-specified object, where each key is the name of a field. Looks like this:

```js
{
  username: {
    isRequired: { message: 'You need to fill out the username' },
    isValidEmail: { message: 'Your username is your e-mail address' },
  },
  password: {
    isRequired: { message: 'You need to fill out the password' },
  },
}
```

I want to run my effect whenever this object changes. New fields might be added, or new keys might be added to existing fields.

If I do `useEffect(() => doStuff(config.fields), [config.fields])`, it'll fire continuously (since this config most likely is specified inline in the function component, and thus will be a new object on every render). If I do `useDeepCompareEffect(() => doStuff(config.fields), [config.fields]), it'll fire only when it changes.

**Comment by kentcdodds** [comment]
What does `doStuff` do?

**Comment by selbekk** [comment]
in my case it's a pure function that runs some validation logic based on `config.fields`.

**Comment by flut1** [comment]
hi @kentcdodds , thanks for writing out an implementation of this hook. I too would rather have an alternative solution, but in this case I cannot think of one. Hopefully you are able to help me out:

I'm writing a `useIntersectionObserver` hook. I want users to be able to pass the optional `IntersectionObserver()` options as an object with [the same syntax](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Creating_an_intersection_observer) as would be used when calling the constructor directly. This will be a new object every time the hook is executed. I need to run an effect only when the options have actually changed.

I think I can get around most of this problem by taking each possible property on the options object, and passing them separately as `useEffect` depedencies:

```
useEffect(() => {
  // re-initialize IntersectionObserver
}, [options.root, options.rootMargin, options.threshold]);
```

There is one problem with this approach though: `options.threshold` is either a number or a number array of arbitrary length. Maybe I can spread the threshold array onto the dependencies array, but I'm not sure `useEffect` supports the dependency array changing length. I also use the `exhaustive-deps` eslint rule, so I would like my dependency array to remain statically analyzable. 

_Sidenote_
I cannot expect users to wrap their options in `useMemo`. Not only because it's not a very friendly API, but also because I [cannot rely](https://reactjs.org/docs/hooks-reference.html#usememo) on `useMemo` as a guarantee that I don't get unnecessary updates. This is particularly relevant for this API, because for some changes I need to create a new instance of `IntersectionObserver`. I don't want to be doing that when the options haven't really changed.

**Comment by kentcdodds** [comment]
Any reason you couldn't do the deep comparison yourself from within the effect callback?

**Comment by flut1** [comment]
I could probably do that, but I would have to store the previous values of the options in some ref/state so I can access and compare them in the next render. It feels like I would be doing the same thing as `useDeepCompareEffect` does internally, but instead have those comparisons clutter my existing logic. Please correct me if I'm wrong about that though

**Comment by vctormb** [comment]
I have a component that receives an object prop that can vary is some situations.  

**Example. First render:**  
```
<Component myObject={{ NAME: 'name', 'AGE': 1, ...more}} />
```  

**Next render can be:**
```
<Component myObject={{ NAME: 'foo', 'AGE': 99, ...more}} />
```

**Next render can change everything:**
```
<Component myObject={{ PHONE: '9999999', 'LASTNAME': 'foo', ...more}} />
```  

That's why I'm using this library, because the object in my app can vary completely.
