### ISSUE TITLE
Question: altering ref during render call

### ISSUE THREAD

**Issue by roman01la** [kentcdodds/use-deep-compare-effect#3]
Hello! Checking in because I'm using a similar approach, but I'm concerned with the fact that in order to track previous dependencies of an effect they should be set on a ref during render call, which is not safe according to docs:

> Conceptually, you can think of refs as similar to instance variables in a class. Unless you’re doing lazy initialization, **avoid setting refs during rendering — this can lead to surprising behavior**. Instead, typically you want to modify refs in event handlers and effects.

https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variables

There it also mention lazy initialization of a ref, but I believe in this case it's more than that. So here I'm questioning if that is safe to do and if not, what exactly can go wrong? 🤔

**Comment by kentcdodds** [comment]
Yes, this is definitely problematic with concurrent mode because in that situation we cannot know for certain that running the render method will result in those react elements actually being committed to the DOM. This is why I have #2 open because I'm kinda thinking it'd be best to deprecate this package due to that issue.

**Comment by roman01la** [comment]
Thanks for clarifying!
