### ISSUE TITLE
useDeepCompareEffect should not be used with dependencies that are all primitive values

### ISSUE THREAD

**Issue by dy** [kentcdodds/use-deep-compare-effect#8]
> use-deep-compare-effect.esm.js:10 Uncaught Error: useDeepCompareEffect should not be used with dependencies that are all primitive values. Use React.useEffect instead.

Sorry for asking - no time to read deep explanations - is that really necessary? What's the significant blocker to just make it a drop-in replacement for useEffect? deepEqual works perfectly fine with primitives.

The problem is that sometimes some deps can be `null`  or `{}`.

**Comment by kentcdodds** [comment]
It's mostly to discourage people from using this as a drop-in replacement for useEffect. It only makes sense for certain scenarios and it can be really harmful for performance in other situations, so I don't want people getting used to just using this all over the place and would prefer that people be more intentional about where it's used. Thanks!

**Comment by MaxMusing** [comment]
@kentcdodds What's the recommended solution if the sole dependency is nullable?

**Comment by drinchev** [comment]
Regarding the same, I'm still a bit scared of that docs section : 

> NOTE: Only use this if your values are objects or arrays that contain objects. Otherwise, you should just use React.useEffect. In case of "polymorphic" values (eg: sometimes object, sometimes a boolean), use useDeepCompareEffectNoCheck, but do it at your own risk, as maybe there can be better approaches to the problem.

What would be a "better approach" for using `undefined | object` type? 

```
const useMyCoolHook = ( someObj? : Array<string> ) => {
  // someObj might be undefined
  useDeepCompareEffect( () => { doStuff(someObj) }, [someObj] );
}
```

I would actually make that error a warning, since making a combo of primitive and object type dependencies would also throw it, which seems like another valid use case.

**Comment by alexandrtovmach** [comment]
@MaxMusing @drinchev @dy 
Dumb solution, but works 🙃
For cases when you have `undefined | null | Array | Object` as dependency you can do:
```
const useMyCoolHook = ( someObj? : Array<string> | null ) => {
  // someObj might be "undefined" or "null"
  useDeepCompareEffect(() => {
    doStuff(someObj)
  }, [someObj || {}]);
}
```
